version: '3.4'

name: reverseproxybenchmark

services:
  reverseproxybenchmark-gateway:
    image: envoyproxy/envoy:v1.31.2
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - reverseproxybenchmark-network
    ports:
      - "41441:80"
        
#  reverseproxybenchmark-gateway:
#    image: reverseproxybenchmark-gateway
#    build:
#      context: .
#      dockerfile: cangjie_gateway/Dockerfile
#    networks:
#      - reverseproxybenchmark-network
#    ports:
#      - "41439:80"
  
  
  reverseproxybenchmark-backendserver-1:
    image: reverseproxybenchmark-backendserver
    build:
      context: .
      dockerfile: BackendServer/Dockerfile
    environment:
      - ServerName=backendserver-1
    networks:
      - reverseproxybenchmark-network
    ports:
      - "41442:8080"


  reverseproxybenchmark-backendserver-2:
    image: reverseproxybenchmark-backendserver
    build:
      context: .
      dockerfile: BackendServer/Dockerfile
    environment:
      - ServerName=backendserver-2
    networks:
      - reverseproxybenchmark-network
    ports:
      - "41443:8080"


  reverseproxybenchmark-backendserver-3:
    image: reverseproxybenchmark-backendserver
    build:
      context: .
      dockerfile: BackendServer/Dockerfile
    environment:
      - ServerName=backendserver-3
    networks:
      - reverseproxybenchmark-network
    ports:
      - "41444:8080"
    


  reverseproxybenchmark-benchmarkserver:
    image: reverseproxybenchmark-benchmarkserver
    build:
      context: .
      dockerfile: BenchmarkServer/Dockerfile
    networks:
      - reverseproxybenchmark-network
    ports:
      - "41440:8080"


networks:
  reverseproxybenchmark-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.173.0/24
